name: Validate Python Code

on:
  - push
  - pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: ["mypy", "ruff check", "ruff format --check"]
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
      - name: Run linter - ${{ matrix.linter }}
        run: uvx ${{ matrix.linter }}
